---
ssh_envs:
  vars:
    sudo_flags: "-HE"
    ansible_port: 22
    ansible_user: root
    ansible_ssh_common_args: "-i {{'{{'}}cops_deploy_ssh_key_paths['deploy'].path}} -p {{'{{'}}ansible_port}} -o IdentitiesOnly=yes"
  hosts:
    {{cookiecutter.dev_host}}:
      ansible_port: "{{cookiecutter.dev_port}}"
    {{cookiecutter.qa_host}}:
      ansible_port: "{{cookiecutter.qa_port}}"
    {{cookiecutter.staging_host}}:
      ansible_port: "{{cookiecutter.staging_port}}"
    {{cookiecutter.prod_host}}:
      ansible_port: "{{cookiecutter.prod_port}}"
dev:
  hosts:
    {{cookiecutter.dev_host}}:
staging:
  hosts:
    {{cookiecutter.staging_host}}:
qa:
  hosts:
    {{cookiecutter.qa_host}}:
prod:
  hosts:
    {{cookiecutter.prod_host}}:
terralegofront_servers:
  children:
    dev:
    qa:
    staging:
    prod:
app_servers: {children: {terralegofront_servers: null}}
controller: {hosts: {localhost: {ansible_connection: local}}}
