version: '3.7'
x-images:
  add_volumes: &volumes
    volumes:
    # package.json/package-lock.json can not be mounted as
    # bind-mount files, it will be harmful !
    - ./:/code
    - ./local/terra{{cookiecutter.app_suffix}}-deploy/prod/etc/nginx/vhost.conf.template:/etc/nginx/conf.d/vhost.conf.template
    - ./local/terra{{cookiecutter.app_suffix}}-deploy/prod/sudoer:/etc/sudoers.d/$APP_TYPE
    # do not mount into ./prod not to clutter the topdir from empty bind mounted files
    - ./local/terra{{cookiecutter.app_suffix}}-deploy/prod/init.sh:/code/init/init.sh
    - ./local/terra{{cookiecutter.app_suffix}}-deploy/prod/start.sh:/code/init/start.sh
    - ./local/terra{{cookiecutter.app_suffix}}-deploy/prod/cron.sh:/code/init/cron.sh
    - ./build:/usr/share/nginx/html
  bypass: &bypass
    command: echo "not started"
    restart: "no"
    entrypoint: echo "not started"
services:
  nginx:
    <<: [ *volumes ]
    ports:
    - "80:80"
    - "443:443"
  cron: {<<: [ *volumes, *bypass ]}
  {{cookiecutter.app_type}}:
    <<: [ *volumes ]
    command: "gosu {{cookiecutter.app_type}} /code/init/start.sh"
    ports:
    - "3000:3000"
