version: "3.7"
x-images:
  x-env:
    env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    <<: [ *env ]
    tty: true
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
services:
  nginx:
    <<: [ *env ]
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_NGINX_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_NGINX_IMAGE_VERSION}"
    volumes:
      - ./local/terra-front-deploy/prod/etc/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - htpasswd:/etc/nginx/htpasswd
      - logs:/logs/
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
volumes:
  logs:
  htpasswd:
