version: "3.7"
x-images:
  x-nginx: &nginx {environment: {RUN_NGINX: "1"}}
  x-env:
    env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    tty: true
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
    command: /bin/bash /code/init/init.sh
services:
  nginx:
    <<: [ *env ]
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_NGINX_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_NGINX_IMAGE_VERSION}"
    command: /code/init/init.sh
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    depends_on:
      - {{cookiecutter.app_type}}
    command: /bin/bash /code/init/cron.sh
