version: '3.7'
services:
  {{cookiecutter.app_type}}:
    build:
      dockerfile: Dockerfile
      context: "."
      args:
        NODE_BASE_NODE_IMAGE:    "$NODE_BASE_NODE_IMAGE"
        NODE_BASE_NODE_VERSION:  "$NODE_BASE_NODE_VERSION"
  nginx:
    build:
      context: "."
      dockerfile: Dockerfile.nginx
      args:
        NODE_BASE_NGINX_IMAGE:   "$NODE_BASE_NGINX_IMAGE"
        NODE_BASE_NGINX_VERSION: "$NODE_BASE_NGINX_VERSION"
        STATICS_FROM: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
